const JobDetailsScreenTranslator = {
  en: {
    title: 'No Any Business Listed Yet',
    postButton: 'Create New Business',
    discription: 'You haven’t posted any business yet. Create your first business listing to get started.',
    closeBusiness: 'Close Business Permanently',
    statusClosed: 'Closed',
    password: '🔒 Password',
    login: 'Login',
    noAccount: 'Don’t have an account? Register',
    alertTitle: 'Error',
    alertMsg: 'Please enter both mobile number and password.',
    alertCloseTitle: 'Confirm Project Closure',
    alertCloseMessage: 'Are you sure you want to close this project? This action cannot be undone.',
    cancel: 'Cancel',
    confirmClose: 'Close Project',
    closedSuccessTitle: 'Project Closed',
    closedSuccessMessage: 'This project has been successfully closed.',
    closedError: 'Failed to close the project. Please try again.',
    error: 'Error',
  },
  hi: {
    title: 'अभी तक आपके पास\nकोई बिज़नेस लिस्ट नहीं है।',
    postButton: 'नया बिज़नेस पोस्ट करें',
    discription: 'आपने अभी तक कोई बिज़नेस लिस्ट नहीं किया है। शुरुआत करने के लिए अपना पहला बिज़नेस जोड़ें।',
    closeBusiness: 'बिज़नेस को हमेशा के लिए बंद करें',
    statusClosed: 'बंद है',
    password: '🔒 पासवर्ड',
    login: 'लॉगिन',
    noAccount: 'कोई खाता नहीं है? पंजीकरण करें',
    alertTitle: 'त्रुटि',
    alertMsg: 'कृपया मोबाइल नंबर और पासवर्ड दर्ज करें।',
    alertCloseTitle: 'बिज़नेस बंद करने की पुष्टि करें',
    alertCloseMessage: 'क्या आप वाकई इस बिज़नेस को हमेशा के लिए बंद करना चाहते हैं? यह क्रिया वापस नहीं ली जा सकती।',
    cancel: 'रद्द करें',
    confirmClose: 'बंद करें',
    closedSuccessTitle: 'बिज़नेस बंद किया गया',
    closedSuccessMessage: 'यह बिज़नेस सफलतापूर्वक बंद कर दिया गया है।',
    closedError: 'बिज़नेस को बंद करने में विफल। कृपया पुनः प्रयास करें।',
    error: 'त्रुटि',
  },
};

export default JobDetailsScreenTranslator;
